resources:
  - url: http://127.0.0.1:5000/mini-thermostat-card.js
    type: module
views:
  - cards:
      - type: custom:mini-thermostat-card
        name: Mini Thermostat Card Development
        entity: sun.sun
        test_gui: true
